name: Build for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install Android NDK and SDK
        run: |
          # Crie um diretório para o Android SDK
          mkdir -p $HOME/android/sdk

          # Baixe e extraia as Ferramentas de Linha de Comando do Android SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk.zip
          unzip -qq android-sdk.zip -d $HOME/android/sdk
          echo "LISTAR ARQUIVOS"
          ls -la $HOME/android/sdk/cmdline-tools
          # Sete ANDROID_HOME e atualize o PATH
          #export ANDROID_HOME=$HOME/android/sdk
          #export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/cmdline-tools/platform-tools

          # Instale os componentes desejados do SDK
          #yes | sdkmanager --licenses
          #sdkmanager "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"

      - name: List Android SDK directory
        run: ls -la $HOME/android/sdk


      #- name: Build Go code for Android
      #  run: |
      #    export GOOS=android
      #    export GOARCH=arm64 # Substitua pelo arquitetura desejada (arm, arm64, x86, x86_64)
      #    go build -o myapp-android-arm64 ./codigo

      #- name: Upload artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: myapp-android-arm64
      #    path: ./myapp-android-arm64
