name: Build for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # Substitua pela versão desejada do Go

      - name: Install Android NDK and SDK
        run: |
          # Baixe e extraia o Android NDK e SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk.zip
          unzip -qq android-sdk.zip -d $HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

          # Instale o SDK do Android
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses # Aceitar todas as licenças
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"

      - name: Build Go code for Android
        run: |
          export GOOS=android
          export GOARCH=arm64 # Substitua pelo arquitetura desejada (arm, arm64, x86, x86_64)
          go build -o myapp-android-arm64 ./codigo

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-android-arm64
          path: ./myapp-android-arm64
