name: Build for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
          
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8        

      - name: Install Android NDK and SDK
        run: |
          # Crie um diretório para o Android SDK
          mkdir -p $HOME/android/sdk

          # Baixe e extraia as Ferramentas de Linha de Comando do Android SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk.zip
          unzip -qq android-sdk.zip -d $HOME
          mkdir -p $HOME/android/sdk/cmdline-tools/latest
          mv $HOME/cmdline-tools/* $HOME/android/sdk/cmdline-tools/latest
          # Sete ANDROID_HOME e atualize o PATH
          export ANDROID_HOME=$HOME/android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          #echo "LISTAR ANDROID_HOME"
          #ls -la $ANDROID_HOME
          echo "LISTAR cmdline-tools"
          ls -la $ANDROID_HOME/cmdline-tools/
          #
          #
          # Instale os componentes desejados do SDK
          #$ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses > /dev/null
          chmod +x $HOME/android/sdk/cmdline-tools/latest/bin/sdkmanager
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses | python yes.py
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"


      #- name: Build Go code for Android
      #  run: |
      #    export GOOS=android
      #    export GOARCH=arm64 # Substitua pelo arquitetura desejada (arm, arm64, x86, x86_64)
      #    go build -o myapp-android-arm64 ./codigo

      #- name: Upload artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: myapp-android-arm64
      #    path: ./myapp-android-arm64
